// ---------------------------------------------------------------------------
// useYearSelectorColors
//
// Replaces the ~350-line switch statement in the original year-selector.
// Each theme entry is one object; the hook picks it and returns it memoized.
// ---------------------------------------------------------------------------

import { useMemo } from 'react';

// Each entry follows the same shape. Values are Tailwind class strings.
const THEMES = {
  pink: {
    text:           'text-pink-700 dark:text-pink-300',
    textBold:       'text-pink-800 dark:text-pink-200',
    textActive:     'text-white',
    bgActive:       'bg-pink-500 dark:bg-pink-600',
    bgHover:        'hover:bg-pink-600/50 dark:hover:bg-pink-700/50',
    bgLight:        'bg-pink-50 dark:bg-pink-900',
    bgLighter:      'bg-pink-100 dark:bg-pink-900',
    bgMed:          'bg-pink-200 dark:bg-pink-800',
    bgDark:         'bg-pink-800 dark:bg-pink-900',
    sidebarBg:      'bg-pink-100 dark:bg-pink-900',
    border:         'border-pink-300 dark:border-pink-700',
    buttonBg:       'bg-pink-600 dark:bg-pink-700',
    buttonHover:    'hover:bg-pink-700 dark:hover:bg-pink-800',
    glowActive:     'shadow-[0_0_15px_rgba(236,72,153,0.7)]',
    toggleColorVar: '[--toggle-shadow:#be185d] dark:[--toggle-shadow:#f9a8d4]',
  },
  purple: {
    text:           'text-purple-700 dark:text-purple-300',
    textBold:       'text-purple-800 dark:text-purple-200',
    textActive:     'text-white',
    bgActive:       'bg-purple-500 dark:bg-purple-600',
    bgHover:        'hover:bg-purple-600/50 dark:hover:bg-purple-700/50',
    bgLight:        'bg-purple-50 dark:bg-purple-900',
    bgLighter:      'bg-purple-100 dark:bg-purple-900',
    bgMed:          'bg-purple-200 dark:bg-purple-800',
    bgDark:         'bg-purple-800 dark:bg-purple-900',
    sidebarBg:      'bg-purple-100 dark:bg-purple-900',
    border:         'border-purple-300 dark:border-purple-700',
    buttonBg:       'bg-purple-600 dark:bg-purple-700',
    buttonHover:    'hover:bg-purple-700 dark:hover:bg-purple-800',
    glowActive:     'shadow-[0_0_15px_rgba(168,85,247,0.7)]',
    toggleColorVar: '[--toggle-shadow:#7e22ce] dark:[--toggle-shadow:#d8b4fe]',
  },
  indigo: {
    text:           'text-indigo-700 dark:text-indigo-300',
    textBold:       'text-indigo-800 dark:text-indigo-200',
    textActive:     'text-white',
    bgActive:       'bg-indigo-500 dark:bg-indigo-600',
    bgHover:        'hover:bg-indigo-600/50 dark:hover:bg-indigo-700/50',
    bgLight:        'bg-indigo-50 dark:bg-indigo-900',
    bgLighter:      'bg-indigo-100 dark:bg-indigo-900',
    bgMed:          'bg-indigo-200 dark:bg-indigo-800',
    bgDark:         'bg-indigo-800 dark:bg-indigo-900',
    sidebarBg:      'bg-indigo-100 dark:bg-indigo-900',
    border:         'border-indigo-300 dark:border-indigo-700',
    buttonBg:       'bg-indigo-600 dark:bg-indigo-700',
    buttonHover:    'hover:bg-indigo-700 dark:hover:bg-indigo-800',
    glowActive:     'shadow-[0_0_15px_rgba(99,102,241,0.7)]',
    toggleColorVar: '[--toggle-shadow:#4338ca] dark:[--toggle-shadow:#a5b4fc]',
  },
  blue: {
    text:           'text-blue-700 dark:text-blue-300',
    textBold:       'text-blue-800 dark:text-blue-200',
    textActive:     'text-white',
    bgActive:       'bg-blue-500 dark:bg-blue-600',
    bgHover:        'hover:bg-blue-600/50 dark:hover:bg-blue-700/50',
    bgLight:        'bg-blue-50 dark:bg-blue-900',
    bgLighter:      'bg-blue-100 dark:bg-blue-900',
    bgMed:          'bg-blue-200 dark:bg-blue-800',
    bgDark:         'bg-blue-800 dark:bg-blue-900',
    sidebarBg:      'bg-blue-100 dark:bg-blue-900',
    border:         'border-blue-300 dark:border-blue-700',
    buttonBg:       'bg-blue-600 dark:bg-blue-700',
    buttonHover:    'hover:bg-blue-700 dark:hover:bg-blue-800',
    glowActive:     'shadow-[0_0_15px_rgba(59,130,246,0.7)]',
    toggleColorVar: '[--toggle-shadow:#1d4ed8] dark:[--toggle-shadow:#93c5fd]',
  },
  green: {
    text:           'text-green-700 dark:text-green-300',
    textBold:       'text-green-800 dark:text-green-200',
    textActive:     'text-white',
    bgActive:       'bg-green-500 dark:bg-green-600',
    bgHover:        'hover:bg-green-600/50 dark:hover:bg-green-700/50',
    bgLight:        'bg-green-50 dark:bg-green-900',
    bgLighter:      'bg-green-100 dark:bg-green-900',
    bgMed:          'bg-green-200 dark:bg-green-800',
    bgDark:         'bg-green-800 dark:bg-green-900',
    sidebarBg:      'bg-green-100 dark:bg-green-900',
    border:         'border-green-300 dark:border-green-700',
    buttonBg:       'bg-green-600 dark:bg-green-700',
    buttonHover:    'hover:bg-green-700 dark:hover:bg-green-800',
    glowActive:     'shadow-[0_0_15px_rgba(34,197,94,0.7)]',
    toggleColorVar: '[--toggle-shadow:#15803d] dark:[--toggle-shadow:#86efac]',
  },
  yellow: {
    text:           'text-yellow-700 dark:text-yellow-300',
    textBold:       'text-yellow-800 dark:text-yellow-200',
    textActive:     'text-white',
    bgActive:       'bg-yellow-500 dark:bg-yellow-600',
    bgHover:        'hover:bg-yellow-600/50 dark:hover:bg-yellow-700/50',
    bgLight:        'bg-yellow-50 dark:bg-yellow-900',
    bgLighter:      'bg-yellow-100 dark:bg-yellow-900',
    bgMed:          'bg-yellow-200 dark:bg-yellow-800',
    bgDark:         'bg-yellow-700 dark:bg-yellow-900',
    sidebarBg:      'bg-yellow-100 dark:bg-yellow-900',
    border:         'border-yellow-300 dark:border-yellow-700',
    buttonBg:       'bg-yellow-500 dark:bg-yellow-700',
    buttonHover:    'hover:bg-yellow-400 dark:hover:bg-yellow-800',
    glowActive:     'shadow-[0_0_15px_rgba(234,179,8,0.7)]',
    toggleColorVar: '[--toggle-shadow:#a16207] dark:[--toggle-shadow:#fde047]',
  },
  red: {
    text:           'text-red-700 dark:text-red-300',
    textBold:       'text-red-800 dark:text-red-200',
    textActive:     'text-white',
    bgActive:       'bg-red-500 dark:bg-red-600',
    bgHover:        'hover:bg-red-600/50 dark:hover:bg-red-700/50',
    bgLight:        'bg-red-50 dark:bg-red-900',
    bgLighter:      'bg-red-100 dark:bg-red-900',
    bgMed:          'bg-red-200 dark:bg-red-800',
    bgDark:         'bg-red-800 dark:bg-red-900',
    sidebarBg:      'bg-red-100 dark:bg-red-900',
    border:         'border-red-300 dark:border-red-700',
    buttonBg:       'bg-red-600 dark:bg-red-700',
    buttonHover:    'hover:bg-red-700 dark:hover:bg-red-800',
    glowActive:     'shadow-[0_0_15px_rgba(239,68,68,0.7)]',
    toggleColorVar: '[--toggle-shadow:#b91c1c] dark:[--toggle-shadow:#fca5a5]',
  },
  orange: {
    text:           'text-orange-700 dark:text-orange-300',
    textBold:       'text-orange-800 dark:text-orange-200',
    textActive:     'text-white',
    bgActive:       'bg-orange-500 dark:bg-orange-600',
    bgHover:        'hover:bg-orange-600/50 dark:hover:bg-orange-700/50',
    bgLight:        'bg-orange-50 dark:bg-orange-900',
    bgLighter:      'bg-orange-100 dark:bg-orange-900',
    bgMed:          'bg-orange-200 dark:bg-orange-800',
    bgDark:         'bg-orange-800 dark:bg-orange-900',
    sidebarBg:      'bg-orange-100 dark:bg-orange-900',
    border:         'border-orange-300 dark:border-orange-700',
    buttonBg:       'bg-orange-600 dark:bg-orange-700',
    buttonHover:    'hover:bg-orange-700 dark:hover:bg-orange-800',
    glowActive:     'shadow-[0_0_15px_rgba(249,115,22,0.7)]',
    toggleColorVar: '[--toggle-shadow:#c2410c] dark:[--toggle-shadow:#fdba74]',
  },
  teal: {
    text:           'text-teal-700 dark:text-teal-300',
    textBold:       'text-teal-800 dark:text-teal-200',
    textActive:     'text-white',
    bgActive:       'bg-teal-500 dark:bg-teal-600',
    bgHover:        'hover:bg-teal-600/50 dark:hover:bg-teal-700/50',
    bgLight:        'bg-teal-50 dark:bg-teal-900',
    bgLighter:      'bg-teal-100 dark:bg-teal-900',
    bgMed:          'bg-teal-200 dark:bg-teal-800',
    bgDark:         'bg-teal-800 dark:bg-teal-900',
    sidebarBg:      'bg-teal-100 dark:bg-teal-900',
    border:         'border-teal-300 dark:border-teal-700',
    buttonBg:       'bg-teal-600 dark:bg-teal-700',
    buttonHover:    'hover:bg-teal-700 dark:hover:bg-teal-800',
    glowActive:     'shadow-[0_0_15px_rgba(20,184,166,0.7)]',
    toggleColorVar: '[--toggle-shadow:#0f766e] dark:[--toggle-shadow:#5eead4]',
  },
  cyan: {
    text:           'text-cyan-700 dark:text-cyan-300',
    textBold:       'text-cyan-800 dark:text-cyan-200',
    textActive:     'text-white',
    bgActive:       'bg-cyan-500 dark:bg-cyan-600',
    bgHover:        'hover:bg-cyan-600/50 dark:hover:bg-cyan-700/50',
    bgLight:        'bg-cyan-50 dark:bg-cyan-900',
    bgLighter:      'bg-cyan-100 dark:bg-cyan-900',
    bgMed:          'bg-cyan-200 dark:bg-cyan-800',
    bgDark:         'bg-cyan-800 dark:bg-cyan-900',
    sidebarBg:      'bg-cyan-100 dark:bg-cyan-900',
    border:         'border-cyan-300 dark:border-cyan-700',
    buttonBg:       'bg-cyan-600 dark:bg-cyan-700',
    buttonHover:    'hover:bg-cyan-700 dark:hover:bg-cyan-800',
    glowActive:     'shadow-[0_0_15px_rgba(6,182,212,0.7)]',
    toggleColorVar: '[--toggle-shadow:#0e7490] dark:[--toggle-shadow:#67e8f9]',
  },
  emerald: {
    text:           'text-emerald-700 dark:text-emerald-300',
    textBold:       'text-emerald-800 dark:text-emerald-200',
    textActive:     'text-white',
    bgActive:       'bg-emerald-500 dark:bg-emerald-600',
    bgHover:        'hover:bg-emerald-600/50 dark:hover:bg-emerald-700/50',
    bgLight:        'bg-emerald-50 dark:bg-emerald-900',
    bgLighter:      'bg-emerald-100 dark:bg-emerald-900',
    bgMed:          'bg-emerald-200 dark:bg-emerald-800',
    bgDark:         'bg-emerald-800 dark:bg-emerald-900',
    sidebarBg:      'bg-emerald-100 dark:bg-emerald-900',
    border:         'border-emerald-300 dark:border-emerald-700',
    buttonBg:       'bg-emerald-600 dark:bg-emerald-700',
    buttonHover:    'hover:bg-emerald-700 dark:hover:bg-emerald-800',
    glowActive:     'shadow-[0_0_15px_rgba(16,185,129,0.7)]',
    toggleColorVar: '[--toggle-shadow:#047857] dark:[--toggle-shadow:#6ee7b7]',
  },
  amber: {
    text:           'text-amber-700 dark:text-amber-300',
    textBold:       'text-amber-800 dark:text-amber-200',
    textActive:     'text-white',
    bgActive:       'bg-amber-500 dark:bg-amber-600',
    bgHover:        'hover:bg-amber-600/50 dark:hover:bg-amber-700/50',
    bgLight:        'bg-amber-50 dark:bg-amber-900',
    bgLighter:      'bg-amber-100 dark:bg-amber-900',
    bgMed:          'bg-amber-200 dark:bg-amber-800',
    bgDark:         'bg-amber-800 dark:bg-amber-900',
    sidebarBg:      'bg-amber-100 dark:bg-amber-900',
    border:         'border-amber-300 dark:border-amber-700',
    buttonBg:       'bg-amber-600 dark:bg-amber-700',
    buttonHover:    'hover:bg-amber-700 dark:hover:bg-amber-800',
    glowActive:     'shadow-[0_0_15px_rgba(245,158,11,0.7)]',
    toggleColorVar: '[--toggle-shadow:#b45309] dark:[--toggle-shadow:#fcd34d]',
  },
  fuchsia: {
    text:           'text-fuchsia-700 dark:text-fuchsia-300',
    textBold:       'text-fuchsia-800 dark:text-fuchsia-200',
    textActive:     'text-white',
    bgActive:       'bg-fuchsia-500 dark:bg-fuchsia-600',
    bgHover:        'hover:bg-fuchsia-600/50 dark:hover:bg-fuchsia-700/50',
    bgLight:        'bg-fuchsia-50 dark:bg-fuchsia-900',
    bgLighter:      'bg-fuchsia-100 dark:bg-fuchsia-900',
    bgMed:          'bg-fuchsia-200 dark:bg-fuchsia-800',
    bgDark:         'bg-fuchsia-800 dark:bg-fuchsia-900',
    sidebarBg:      'bg-fuchsia-100 dark:bg-fuchsia-900',
    border:         'border-fuchsia-300 dark:border-fuchsia-700',
    buttonBg:       'bg-fuchsia-600 dark:bg-fuchsia-700',
    buttonHover:    'hover:bg-fuchsia-700 dark:hover:bg-fuchsia-800',
    glowActive:     'shadow-[0_0_15px_rgba(217,70,239,0.7)]',
    toggleColorVar: '[--toggle-shadow:#a21caf] dark:[--toggle-shadow:#f0abfc]',
  },
  violet: {
    text:           'text-violet-700 dark:text-violet-300',
    textBold:       'text-violet-800 dark:text-violet-200',
    textActive:     'text-white',
    bgActive:       'bg-violet-500 dark:bg-violet-600',
    bgHover:        'hover:bg-violet-600/50 dark:hover:bg-violet-700/50',
    bgLight:        'bg-violet-50 dark:bg-violet-900',
    bgLighter:      'bg-violet-100 dark:bg-violet-900',
    bgMed:          'bg-violet-200 dark:bg-violet-800',
    bgDark:         'bg-violet-800 dark:bg-violet-900',
    sidebarBg:      'bg-violet-100 dark:bg-violet-900',
    border:         'border-violet-300 dark:border-violet-700',
    buttonBg:       'bg-violet-600 dark:bg-violet-700',
    buttonHover:    'hover:bg-violet-700 dark:hover:bg-violet-800',
    glowActive:     'shadow-[0_0_15px_rgba(139,92,246,0.7)]',
    toggleColorVar: '[--toggle-shadow:#6d28d9] dark:[--toggle-shadow:#c4b5fd]',
  },
  rose: {
    text:           'text-rose-700 dark:text-rose-300',
    textBold:       'text-rose-800 dark:text-rose-200',
    textActive:     'text-white',
    bgActive:       'bg-rose-500 dark:bg-rose-600',
    bgHover:        'hover:bg-rose-600/50 dark:hover:bg-rose-700/50',
    bgLight:        'bg-rose-50 dark:bg-rose-900',
    bgLighter:      'bg-rose-100 dark:bg-rose-900',
    bgMed:          'bg-rose-200 dark:bg-rose-800',
    bgDark:         'bg-rose-800 dark:bg-rose-900',
    sidebarBg:      'bg-rose-100 dark:bg-rose-900',
    border:         'border-rose-300 dark:border-rose-700',
    buttonBg:       'bg-rose-600 dark:bg-rose-700',
    buttonHover:    'hover:bg-rose-700 dark:hover:bg-rose-800',
    glowActive:     'shadow-[0_0_15px_rgba(244,63,94,0.7)]',
    toggleColorVar: '[--toggle-shadow:#be123c] dark:[--toggle-shadow:#fda4af]',
  },
};

const MINIMAL = {
  text:           'text-black dark:text-white',
  textBold:       'text-black dark:text-white',
  textActive:     'text-white dark:text-black',
  bgActive:       'bg-black dark:bg-white',
  bgHover:        'hover:bg-gray-200 dark:hover:bg-gray-800',
  bgLight:        'bg-white dark:bg-black',
  bgLighter:      'bg-white dark:bg-black',
  bgMed:          'bg-gray-200 dark:bg-gray-800',
  bgDark:         'bg-black dark:bg-black',
  sidebarBg:      'bg-white dark:bg-black',
  border:         'border-black dark:border-[#4169E1]',
  buttonBg:       'bg-black dark:bg-white',
  buttonHover:    'hover:bg-gray-800 dark:hover:bg-gray-200',
  glowActive:     'shadow-[0_0_15px_rgba(0,0,0,0.3)] dark:shadow-[0_0_15px_rgba(65,105,225,0.4)]',
  toggleColorVar: '[--toggle-shadow:black] dark:[--toggle-shadow:#4169E1]',
};

export function useYearSelectorColors({ colorTheme = 'teal', colorMode = 'colorful' }) {
  return useMemo(() => {
    if (colorMode === 'minimal') return MINIMAL;
    return THEMES[colorTheme] ?? THEMES.teal;
  }, [colorTheme, colorMode]);
}

// Also export the raw map so components can look up a theme by name without the hook
export { THEMES, MINIMAL };
