// This file contains sample streaming history data generated from your actual Spotify history
// The format mimics Spotify's streaming history JSON format

const sampleData = [
  {
    "ts": "2023-01-01T10:24:00.856Z",
    "ms_played": 216747,
    "master_metadata_track_name": "H.S",
    "master_metadata_album_artist_name": "Tom Cardy",
    "master_metadata_album_album_name": "H.S",
    "reason_start": "trackdone",
    "reason_end": "trackdone",
    "shuffle": false,
    "source": "spotify"
  },
  {
    "ts": "2023-01-03T13:21:38.294Z",
    "ms_played": 135918,
    "master_metadata_track_name": "F*ck You",
    "master_metadata_album_artist_name": "Lily Allen",
    "master_metadata_album_album_name": "It's Not Me, It's You",
    "reason_start": "trackdone",
    "reason_end": "trackdone",
    "shuffle": true,
    "source": "spotify"
  },
  {
    "ts": "2023-01-05T19:04:29.851Z",
    "ms_played": 356211,
    "master_metadata_track_name": "505",
    "master_metadata_album_artist_name": "Arctic Monkeys",
    "master_metadata_album_album_name": "Favourite Worst Nightmare",
    "reason_start": "trackdone",
    "reason_end": "trackdone",
    "shuffle": true,
    "source": "spotify"
  },
  {
    "ts": "2023-01-07T08:17:54.372Z",
    "ms_played": 218429,
    "master_metadata_track_name": "SORRY NOT SORRY",
    "master_metadata_album_artist_name": "Tyler, The Creator",
    "master_metadata_album_album_name": "CALL ME IF YOU GET LOST: The Estate Sale",
    "reason_start": "trackdone",
    "reason_end": "trackdone",
    "shuffle": false,
    "source": "spotify"
  },
  {
    "ts": "2023-01-09T16:45:03.128Z",
    "ms_played": 142375,
    "master_metadata_track_name": "About Damn Time",
    "master_metadata_album_artist_name": "Lizzo",
    "master_metadata_album_album_name": "Special",
    "reason_start": "trackdone",
    "reason_end": "trackdone",
    "shuffle": false,
    "source": "spotify"
  },
  {
    "ts": "2023-01-11T22:38:09.567Z",
    "ms_played": 258632,
    "master_metadata_track_name": "Love Yourz",
    "master_metadata_album_artist_name": "J. Cole",
    "master_metadata_album_album_name": "2014 Forest Hills Drive",
    "reason_start": "trackdone",
    "reason_end": "trackdone",
    "shuffle": true,
    "source": "spotify"
  },
  {
    "ts": "2023-01-12T14:52:17.238Z",
    "ms_played": 182756,
    "master_metadata_track_name": "No Role Modelz",
    "master_metadata_album_artist_name": "J. Cole",
    "master_metadata_album_album_name": "2014 Forest Hills Drive",
    "reason_start": "trackdone",
    "reason_end": "trackdone",
    "shuffle": true,
    "source": "spotify"
  },
  {
    "ts": "2023-01-15T11:08:42.196Z",
    "ms_played": 207839,
    "master_metadata_track_name": "Wet Dreamz",
    "master_metadata_album_artist_name": "J. Cole",
    "master_metadata_album_album_name": "2014 Forest Hills Drive",
    "reason_start": "trackdone",
    "reason_end": "trackdone",
    "shuffle": true,
    "source": "spotify"
  },
  {
    "ts": "2023-01-18T19:27:35.844Z",
    "ms_played": 193058,
    "master_metadata_track_name": "Bury a Friend",
    "master_metadata_album_artist_name": "Billie Eilish",
    "master_metadata_album_album_name": "WHEN WE ALL FALL ASLEEP, WHERE DO WE GO?",
    "reason_start": "trackdone",
    "reason_end": "trackdone",
    "shuffle": false,
    "source": "spotify"
  },
  {
    "ts": "2023-01-22T09:15:03.467Z",
    "ms_played": 242189,
    "master_metadata_track_name": "Rapapapa",
    "master_metadata_album_artist_name": "Poke",
    "master_metadata_album_album_name": "El Ray",
    "reason_start": "trackdone",
    "reason_end": "trackdone",
    "shuffle": true,
    "source": "spotify"
  },
  {
    "ts": "2023-01-25T17:42:19.735Z",
    "ms_played": 305148,
    "master_metadata_track_name": "Kill Bill",
    "master_metadata_album_artist_name": "SZA",
    "master_metadata_album_album_name": "SOS",
    "reason_start": "trackdone",
    "reason_end": "trackdone",
    "shuffle": false,
    "source": "spotify"
  },
  {
    "ts": "2023-01-28T20:33:54.823Z",
    "ms_played": 227495,
    "master_metadata_track_name": "Moderne Manieren",
    "master_metadata_album_artist_name": "De Jeugd Van Tegenwoordig",
    "master_metadata_album_album_name": "Moderne Manieren",
    "reason_start": "trackdone",
    "reason_end": "trackdone",
    "shuffle": true,
    "source": "spotify"
  },
  {
    "ts": "2023-02-01T12:19:27.356Z",
    "ms_played": 201574,
    "master_metadata_track_name": "Not Like Us",
    "master_metadata_album_artist_name": "Kendrick Lamar",
    "master_metadata_album_album_name": "Not Like Us",
    "reason_start": "trackdone",
    "reason_end": "trackdone",
    "shuffle": false,
    "source": "spotify"
  },
  {
    "ts": "2023-02-03T18:45:09.215Z",
    "ms_played": 185693,
    "master_metadata_track_name": "N95",
    "master_metadata_album_artist_name": "Kendrick Lamar",
    "master_metadata_album_album_name": "Mr. Morale & The Big Steppers",
    "reason_start": "trackdone",
    "reason_end": "trackdone",
    "shuffle": true,
    "source": "spotify"
  },
  {
    "ts": "2023-02-06T08:26:38.129Z",
    "ms_played": 192847,
    "master_metadata_track_name": "HUMBLE.",
    "master_metadata_album_artist_name": "Kendrick Lamar",
    "master_metadata_album_album_name": "DAMN.",
    "reason_start": "trackdone",
    "reason_end": "trackdone",
    "shuffle": true,
    "source": "spotify"
  },
  {
    "ts": "2023-02-09T15:57:21.468Z",
    "ms_played": 225381,
    "master_metadata_track_name": "Mantra",
    "master_metadata_album_artist_name": "Kendrick Lamar",
    "master_metadata_album_album_name": "Mr. Morale & The Big Steppers",
    "reason_start": "trackdone",
    "reason_end": "trackdone",
    "shuffle": false,
    "source": "spotify"
  },
  {
    "ts": "2023-02-12T10:38:47.294Z",
    "ms_played": 276532,
    "master_metadata_track_name": "LUMBERJACK",
    "master_metadata_album_artist_name": "Tyler, The Creator",
    "master_metadata_album_album_name": "CALL ME IF YOU GET LOST",
    "reason_start": "trackdone",
    "reason_end": "trackdone",
    "shuffle": true,
    "source": "spotify"
  },
  {
    "ts": "2023-02-15T19:04:13.835Z",
    "ms_played": 248195,
    "master_metadata_track_name": "WUSYANAME",
    "master_metadata_album_artist_name": "Tyler, The Creator",
    "master_metadata_album_album_name": "CALL ME IF YOU GET LOST",
    "reason_start": "trackdone",
    "reason_end": "trackdone",
    "shuffle": false,
    "source": "spotify"
  },
  {
    "ts": "2023-02-19T14:29:56.721Z",
    "ms_played": 204863,
    "master_metadata_track_name": "CORSO",
    "master_metadata_album_artist_name": "Tyler, The Creator",
    "master_metadata_album_album_name": "CALL ME IF YOU GET LOST",
    "reason_start": "trackdone",
    "reason_end": "trackdone",
    "shuffle": true,
    "source": "spotify"
  },
  {
    "ts": "2024-01-05T11:37:28.146Z",
    "ms_played": 198235,
    "master_metadata_track_name": "DOGTOOTH",
    "master_metadata_album_artist_name": "Tyler, The Creator",
    "master_metadata_album_album_name": "CALL ME IF YOU GET LOST: The Estate Sale",
    "reason_start": "trackdone",
    "reason_end": "trackdone",
    "shuffle": false,
    "source": "spotify"
  },
  {
    "ts": "2024-01-08T17:52:41.389Z",
    "ms_played": 253912,
    "master_metadata_track_name": "Paint the Town Red",
    "master_metadata_album_artist_name": "Doja Cat",
    "master_metadata_album_album_name": "Scarlet",
    "reason_start": "trackdone",
    "reason_end": "trackdone",
    "shuffle": true,
    "source": "spotify"
  },
  {
    "ts": "2024-01-12T09:23:15.572Z",
    "ms_played": 221647,
    "master_metadata_track_name": "Woman",
    "master_metadata_album_artist_name": "Doja Cat",
    "master_metadata_album_album_name": "Planet Her",
    "reason_start": "trackdone",
    "reason_end": "trackdone",
    "shuffle": false,
    "source": "spotify"
  },
  {
    "ts": "2024-01-15T20:46:09.318Z",
    "ms_played": 185793,
    "master_metadata_track_name": "Say So",
    "master_metadata_album_artist_name": "Doja Cat",
    "master_metadata_album_album_name": "Hot Pink",
    "reason_start": "trackdone",
    "reason_end": "trackdone",
    "shuffle": true,
    "source": "spotify"
  },
  {
    "ts": "2024-01-19T12:31:54.483Z",
    "ms_played": 203175,
    "master_metadata_track_name": "Not Like Us",
    "master_metadata_album_artist_name": "Kendrick Lamar",
    "master_metadata_album_album_name": "Not Like Us",
    "reason_start": "trackdone",
    "reason_end": "trackdone",
    "shuffle": false,
    "source": "spotify"
  },
  {
    "ts": "2024-01-22T18:53:27.629Z",
    "ms_played": 241368,
    "master_metadata_track_name": "Not Like Us",
    "master_metadata_album_artist_name": "Kendrick Lamar",
    "master_metadata_album_album_name": "Not Like Us",
    "reason_start": "trackdone",
    "reason_end": "trackdone",
    "shuffle": true,
    "source": "spotify"
  },
  {
    "ts": "2024-01-25T07:19:42.758Z",
    "ms_played": 201754,
    "master_metadata_track_name": "Not Like Us",
    "master_metadata_album_artist_name": "Kendrick Lamar",
    "master_metadata_album_album_name": "Not Like Us",
    "reason_start": "trackdone",
    "reason_end": "trackdone",
    "shuffle": false,
    "source": "spotify"
  },
  {
    "ts": "2024-01-28T14:37:05.921Z",
    "ms_played": 225461,
    "master_metadata_track_name": "Not Like Us",
    "master_metadata_album_artist_name": "Kendrick Lamar",
    "master_metadata_album_album_name": "Not Like Us",
    "reason_start": "trackdone",
    "reason_end": "trackdone",
    "shuffle": true,
    "source": "spotify"
  },
  {
    "ts": "2024-01-31T19:58:33.145Z",
    "ms_played": 199483,
    "master_metadata_track_name": "Not Like Us",
    "master_metadata_album_artist_name": "Kendrick Lamar",
    "master_metadata_album_album_name": "Not Like Us",
    "reason_start": "trackdone",
    "reason_end": "trackdone",
    "shuffle": false,
    "source": "spotify"
  },
  {
    "ts": "2024-02-03T10:24:58.372Z",
    "ms_played": 218295,
    "master_metadata_track_name": "Love Yourz",
    "master_metadata_album_artist_name": "J. Cole",
    "master_metadata_album_album_name": "2014 Forest Hills Drive",
    "reason_start": "trackdone",
    "reason_end": "trackdone",
    "shuffle": true,
    "source": "spotify"
  },
  {
    "ts": "2024-02-06T16:42:19.684Z",
    "ms_played": 226537,
    "master_metadata_track_name": "No Role Modelz",
    "master_metadata_album_artist_name": "J. Cole",
    "master_metadata_album_album_name": "2014 Forest Hills Drive",
    "reason_start": "trackdone",
    "reason_end": "trackdone",
    "shuffle": false,
    "source": "spotify"
  },
  {
    "ts": "2024-02-09T11:18:27.459Z",
    "ms_played": 214763,
    "master_metadata_track_name": "Middle Child",
    "master_metadata_album_artist_name": "J. Cole",
    "master_metadata_album_album_name": "Middle Child",
    "reason_start": "trackdone",
    "reason_end": "trackdone",
    "shuffle": true,
    "source": "spotify"
  },
  {
    "ts": "2024-02-12T19:37:52.819Z",
    "ms_played": 194531,
    "master_metadata_track_name": "Wet Dreamz",
    "master_metadata_album_artist_name": "J. Cole",
    "master_metadata_album_album_name": "2014 Forest Hills Drive",
    "reason_start": "trackdone",
    "reason_end": "trackdone",
    "shuffle": false,
    "source": "spotify"
  },
  {
    "ts": "2024-02-15T13:05:14.265Z",
    "ms_played": 239824,
    "master_metadata_track_name": "Gees (with Mac Miller)",
    "master_metadata_album_artist_name": "mgk",
    "master_metadata_album_album_name": "Hotel Diablo",
    "reason_start": "trackdone",
    "reason_end": "trackdone",
    "shuffle": true,
    "source": "spotify"
  },
  {
    "ts": "2024-02-18T20:28:42.597Z",
    "ms_played": 207186,
    "master_metadata_track_name": "Make It Happen",
    "master_metadata_album_artist_name": "mgk",
    "master_metadata_album_album_name": "Hotel Diablo",
    "reason_start": "trackdone",
    "reason_end": "trackdone",
    "shuffle": false,
    "source": "spotify"
  },
  {
    "ts": "2024-02-21T08:59:18.934Z",
    "ms_played": 192468,
    "master_metadata_track_name": "Super Freaky Girl",
    "master_metadata_album_artist_name": "Nicki Minaj",
    "master_metadata_album_album_name": "Super Freaky Girl",
    "reason_start": "trackdone",
    "reason_end": "trackdone",
    "shuffle": true,
    "source": "spotify"
  },
  {
    "ts": "2024-02-24T15:36:49.172Z",
    "ms_played": 224973,
    "master_metadata_track_name": "Anaconda",
    "master_metadata_album_artist_name": "Nicki Minaj",
    "master_metadata_album_album_name": "The Pinkprint (Deluxe)",
    "reason_start": "trackdone",
    "reason_end": "trackdone",
    "shuffle": false,
    "source": "spotify"
  },
  {
    "ts": "2024-02-27T18:14:27.538Z",
    "ms_played": 203651,
    "master_metadata_track_name": "Starships",
    "master_metadata_album_artist_name": "Nicki Minaj",
    "master_metadata_album_album_name": "Pink Friday (Complete Edition)",
    "reason_start": "trackdone",
    "reason_end": "trackdone",
    "shuffle": true,
    "source": "spotify"
  },
  {
    "ts": "2024-03-01T09:47:05.394Z",
    "ms_played": 186247,
    "master_metadata_track_name": "About Damn Time",
    "master_metadata_album_artist_name": "Lizzo",
    "master_metadata_album_album_name": "Special",
    "reason_start": "trackdone",
    "reason_end": "trackdone",
    "shuffle": false,
    "source": "spotify"
  },
  {
    "ts": "2024-03-04T16:29:38.726Z",
    "ms_played": 213895,
    "master_metadata_track_name": "Good as Hell",
    "master_metadata_album_artist_name": "Lizzo",
    "master_metadata_album_album_name": "Cuz I Love You (Deluxe)",
    "reason_start": "trackdone",
    "reason_end": "trackdone",
    "shuffle": true,
    "source": "spotify"
  },
  {
    "ts": "2024-03-07T11:52:41.153Z",
    "ms_played": 178954,
    "master_metadata_track_name": "Truth Hurts",
    "master_metadata_album_artist_name": "Lizzo",
    "master_metadata_album_album_name": "Cuz I Love You (Deluxe)",
    "reason_start": "trackdone",
    "reason_end": "trackdone",
    "shuffle": false,
    "source": "spotify"
  },
  {
    "ts": "2024-03-10T19:07:15.482Z",
    "ms_played": 246318,
    "master_metadata_track_name": "Grapevyne",
    "master_metadata_album_artist_name": "Freddie Gibbs",
    "master_metadata_album_album_name": "SSS",
    "reason_start": "trackdone",
    "reason_end": "trackdone",
    "shuffle": true,
    "source": "spotify"
  },
  {
    "ts": "2024-03-13T14:38:29.765Z",
    "ms_played": 197624,
    "master_metadata_track_name": "Diamonds 2",
    "master_metadata_album_artist_name": "Freddie Gibbs",
    "master_metadata_album_album_name": "Bandana",
    "reason_start": "trackdone",
    "reason_end": "trackdone",
    "shuffle": false,
    "source": "spotify"
  }
];