import React, { useState } from 'react';
import { FileText, Copy, Check } from 'lucide-react';
import { useTheme } from './themeprovider.js';
import TopNStepper from './TopNStepper.js';

const Top100Export = ({
  processedData = [],
  songsByYear = {},
  topArtists = [],
  topAlbums = [],
  formatDuration,
  colorMode = 'minimal'
}) => {
  const { theme } = useTheme();
  const isDarkMode = theme === 'dark';
  const isColorful = colorMode === 'colorful';
  const [copied, setCopied] = useState(false);
  const [trackCount, setTrackCount] = useState(100);

  const buildTop100JSON = () => {
    const formatMs = (ms) => {
      if (!ms) return '0m';
      const hours = Math.floor(ms / 3600000);
      const minutes = Math.floor((ms % 3600000) / 60000);
      if (hours > 0) return `${hours}h ${minutes}m`;
      return `${minutes}m`;
    };

    const mapTrack = (track, rank) => ({
      rank,
      track: track.displayName || track.trackName,
      artist: track.displayArtist || track.fullArtist || track.artist,
      album: track.albumName || 'Unknown Album',
      plays: track.playCount,
      totalListened: formatMs(track.totalPlayed)
    });

    // All-time top N
    const allTime = processedData
      .slice(0, trackCount)
      .map((t, i) => mapTrack(t, i + 1));

    // Per-year top 100
    const yearly = {};
    const years = Object.keys(songsByYear).sort((a, b) => b - a);
    for (const year of years) {
      yearly[year] = (songsByYear[year] || [])
        .slice(0, 100)
        .map((t, i) => mapTrack(t, i + 1));
    }

    // Top 50 artists
    const artists = topArtists
      .slice(0, 50)
      .map((a, i) => ({
        rank: i + 1,
        artist: a.name,
        plays: a.playCount,
        totalListened: formatMs(a.totalPlayed)
      }));

    // Top 50 albums
    const albums = topAlbums
      .slice(0, 50)
      .map((a, i) => ({
        rank: i + 1,
        album: a.name,
        artist: a.artist,
        plays: a.playCount,
        totalListened: formatMs(a.totalPlayed)
      }));

    return {
      exportedAt: new Date().toISOString(),
      description: 'Streaming history top rankings - generated by cake dreamin\'',
      [`allTimeTop${trackCount}`]: allTime,
      yearlyTop100: yearly,
      topArtists: artists,
      topAlbums: albums
    };
  };

  const handleDownload = () => {
    const data = buildTop100JSON();
    const jsonString = JSON.stringify(data, null, 2);
    const blob = new Blob([jsonString], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `top-${trackCount}-rankings-${new Date().toISOString().split('T')[0]}.json`;
    document.body.appendChild(link);
    link.click();
    setTimeout(() => {
      URL.revokeObjectURL(url);
      document.body.removeChild(link);
    }, 100);
  };

  const handleCopyToClipboard = async () => {
    const data = buildTop100JSON();
    const jsonString = JSON.stringify(data, null, 2);
    try {
      await navigator.clipboard.writeText(jsonString);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Fallback for older browsers
      const textarea = document.createElement('textarea');
      textarea.value = jsonString;
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand('copy');
      document.body.removeChild(textarea);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  const maxTracks = Math.min(processedData.length, 250);

  return (
    <div className="flex flex-wrap items-center gap-2 mt-2">
      <TopNStepper
        value={trackCount}
        setValue={setTrackCount}
        max={maxTracks}
        inputClass={
          isColorful
            ? 'border-black bg-green-100 text-black focus:outline-none focus:border-green-700 dark:border-green-600 dark:bg-black dark:text-green-300 dark:focus:border-green-400'
            : (isDarkMode ? 'border-[#4169E1] bg-black text-[#FDF6E3] focus:outline-none focus:border-blue-400' : 'border-black bg-white text-black focus:outline-none focus:border-gray-500')
        }
        buttonClass={
          isColorful
            ? 'text-black dark:text-green-400'
            : (isDarkMode ? 'text-[#FDF6E3]' : 'text-black')
        }
      />
      <button
        onClick={handleDownload}
        className={
          isColorful
            ? 'flex items-center gap-1.5 px-2 py-1 text-xs sm:px-3 sm:py-1.5 sm:text-sm bg-cyan-600 text-white rounded hover:bg-cyan-700 transition-colors'
            : `flex items-center gap-1.5 px-2 py-1 text-xs sm:px-3 sm:py-1.5 sm:text-sm rounded transition-colors ${isDarkMode ? 'bg-black text-[#FDF6E3] border border-[#4169E1] hover:bg-gray-800' : 'bg-white text-black border border-black hover:bg-gray-100'}`
        }
      >
        <FileText size={14} />
        Top {trackCount} JSON
      </button>
      <button
        onClick={handleCopyToClipboard}
        className={
          isColorful
            ? 'flex items-center gap-1.5 px-2 py-1 text-xs sm:px-3 sm:py-1.5 sm:text-sm bg-teal-600 text-white rounded hover:bg-teal-700 transition-colors'
            : `flex items-center gap-1.5 px-2 py-1 text-xs sm:px-3 sm:py-1.5 sm:text-sm rounded transition-colors ${isDarkMode ? 'bg-black text-[#FDF6E3] border border-[#4169E1] hover:bg-gray-800' : 'bg-white text-black border border-black hover:bg-gray-100'}`
        }
      >
        {copied ? <Check size={14} /> : <Copy size={14} />}
        {copied ? 'Copied!' : 'Copy for AI'}
      </button>
    </div>
  );
};

export default Top100Export;
