import React, { useState } from 'react';
import { FileText, Copy, Check } from 'lucide-react';
import { useTheme } from './themeprovider.js';

const Top100Export = ({
  processedData = [],
  songsByYear = {},
  topArtists = [],
  topAlbums = [],
  formatDuration,
  colorMode = 'minimal'
}) => {
  const { theme } = useTheme();
  const isDarkMode = theme === 'dark';
  const isColorful = colorMode === 'colorful';
  const [copied, setCopied] = useState(false);
  const [trackCount, setTrackCount] = useState(100);

  const buildTop100JSON = () => {
    const formatMs = (ms) => {
      if (!ms) return '0m';
      const hours = Math.floor(ms / 3600000);
      const minutes = Math.floor((ms % 3600000) / 60000);
      if (hours > 0) return `${hours}h ${minutes}m`;
      return `${minutes}m`;
    };

    const mapTrack = (track, rank) => ({
      rank,
      track: track.displayName || track.trackName,
      artist: track.displayArtist || track.fullArtist || track.artist,
      album: track.albumName || 'Unknown Album',
      plays: track.playCount,
      totalListened: formatMs(track.totalPlayed)
    });

    // All-time top N
    const allTime = processedData
      .slice(0, trackCount)
      .map((t, i) => mapTrack(t, i + 1));

    // Per-year top 100
    const yearly = {};
    const years = Object.keys(songsByYear).sort((a, b) => b - a);
    for (const year of years) {
      yearly[year] = (songsByYear[year] || [])
        .slice(0, 100)
        .map((t, i) => mapTrack(t, i + 1));
    }

    // Top 50 artists
    const artists = topArtists
      .slice(0, 50)
      .map((a, i) => ({
        rank: i + 1,
        artist: a.name,
        plays: a.playCount,
        totalListened: formatMs(a.totalPlayed)
      }));

    // Top 50 albums
    const albums = topAlbums
      .slice(0, 50)
      .map((a, i) => ({
        rank: i + 1,
        album: a.name,
        artist: a.artist,
        plays: a.playCount,
        totalListened: formatMs(a.totalPlayed)
      }));

    return {
      exportedAt: new Date().toISOString(),
      description: 'Streaming history top rankings - generated by cake dreamin\'',
      [`allTimeTop${trackCount}`]: allTime,
      yearlyTop100: yearly,
      topArtists: artists,
      topAlbums: albums
    };
  };

  const handleDownload = () => {
    const data = buildTop100JSON();
    const jsonString = JSON.stringify(data, null, 2);
    const blob = new Blob([jsonString], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `top-${trackCount}-rankings-${new Date().toISOString().split('T')[0]}.json`;
    document.body.appendChild(link);
    link.click();
    setTimeout(() => {
      URL.revokeObjectURL(url);
      document.body.removeChild(link);
    }, 100);
  };

  const handleCopyToClipboard = async () => {
    const data = buildTop100JSON();
    const jsonString = JSON.stringify(data, null, 2);
    try {
      await navigator.clipboard.writeText(jsonString);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Fallback for older browsers
      const textarea = document.createElement('textarea');
      textarea.value = jsonString;
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand('copy');
      document.body.removeChild(textarea);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  const maxTracks = Math.min(processedData.length, 250);

  return (
    <div className="flex flex-wrap items-center gap-2 mt-2">
      <input
        type="number"
        min={1}
        max={maxTracks}
        value={trackCount}
        onChange={(e) => {
          const val = Math.max(1, Math.min(maxTracks, parseInt(e.target.value) || 1));
          setTrackCount(val);
        }}
        className={
          isColorful
            ? 'w-16 px-2 py-2 bg-cyan-900 text-white rounded text-sm text-center border border-cyan-600 focus:outline-none focus:border-cyan-400'
            : `w-16 px-2 py-2 rounded text-sm text-center focus:outline-none ${isDarkMode ? 'bg-black text-white border border-[#4169E1] focus:border-blue-400' : 'bg-white text-black border border-black focus:border-gray-500'}`
        }
      />
      <button
        onClick={handleDownload}
        className={
          isColorful
            ? 'flex items-center gap-2 px-4 py-2 bg-cyan-600 text-white rounded hover:bg-cyan-700 transition-colors text-sm'
            : `flex items-center gap-2 px-4 py-2 rounded transition-colors text-sm ${isDarkMode ? 'bg-black text-white border border-[#4169E1] hover:bg-gray-800' : 'bg-white text-black border border-black hover:bg-gray-100'}`
        }
      >
        <FileText size={16} />
        Top {trackCount} JSON
      </button>
      <button
        onClick={handleCopyToClipboard}
        className={
          isColorful
            ? 'flex items-center gap-2 px-4 py-2 bg-teal-600 text-white rounded hover:bg-teal-700 transition-colors text-sm'
            : `flex items-center gap-2 px-4 py-2 rounded transition-colors text-sm ${isDarkMode ? 'bg-black text-white border border-[#4169E1] hover:bg-gray-800' : 'bg-white text-black border border-black hover:bg-gray-100'}`
        }
      >
        {copied ? <Check size={16} /> : <Copy size={16} />}
        {copied ? 'Copied!' : 'Copy for AI'}
      </button>
    </div>
  );
};

export default Top100Export;
